aliases:
  coding:
    description: Aggregated Leaderboard Top Coding Models
    strategy: chain_fallback
    candidates:
    - provider: g4f
      model: claude-opus-4-5
    - provider: gemini
      model: gemini-3-flash
    - provider: g4f
      model: claude-opus-4-6
    - provider: gemini
      model: gemini-3-pro
    - provider: cerebras
      model: glm-5
    - provider: together
      model: deepseek-chat
  smart:
    description: Highest Agentic Coding Score
    strategy: chain_fallback
    candidates:
    - provider: gemini
      model: gemini-3-flash
    - provider: g4f
      model: claude-opus-4-5
    - provider: g4f
      model: gpt-5-2
    - provider: gemini
      model: gemini-3-pro
  fast:
    description: Highest TPS (Quality > 40)
    strategy: chain_fallback
    candidates:
    - provider: g4f
      model: gpt-5-2
    - provider: gemini
      model: gemini-3-flash
    - provider: gemini
      model: gemini-3-pro
