#!/bin/bash
#
# CLIProxyAPI VPS Deployment Script
#
# This script installs and configures CLIProxyAPI on an Oracle Micro VPS
# (1GB RAM + ZRAM + 4GB swap). Designed to run alongside your existing
# LLM gateway.
#
# Usage:
#   chmod +x install_cliproxyapi.sh
#   sudo ./install_cliproxyapi.sh
#
# IMPORTANT for iFlow: Use cookie authentication, NOT OAuth!
#   OAuth tokens expire every 7 days with no auto-refresh.
#   Cookie sessions last months and auto-refresh automatically.
#

set -e

# Configuration
CLIPROXYAPI_VERSION="v6.9.19"
INSTALL_DIR="/opt/cliproxyapi"
CONFIG_DIR="${INSTALL_DIR}/config"
AUTH_DIR="${INSTALL_DIR}/auth"
LOG_DIR="/var/log/cliproxyapi"
SERVICE_USER="cliproxyapi"
SERVICE_GROUP="cliproxyapi"
PORT="${CLIPROXYAPI_PORT:-8317}"
BASE_URL="${CLIPROXYAPI_BASE_URL:-http://127.0.0.1:${PORT}}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_requirements() {
    log_info "Checking system requirements..."

    # Check if running as root
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root (use sudo)"
        exit 1
    fi

    # Check architecture
    ARCH=$(uname -m)
    if [[ "$ARCH" == "x86_64" ]]; then
        BINARY_NAME="cli-proxy-api-linux-amd64"
    elif [[ "$ARCH" == "aarch64" ]]; then
        BINARY_NAME="cli-proxy-api-linux-arm64"
    else
        log_error "Unsupported architecture: $ARCH"
        exit 1
    fi

    log_info "Architecture: $ARCH, Binary: $BINARY_NAME"

    # Check available memory
    TOTAL_MEM=$(free -m | awk '/^Mem:/{print $2}')
    log_info "Total memory: ${TOTAL_MEM}MB"

    if [[ $TOTAL_MEM -lt 512 ]]; then
        log_warn "Low memory detected (<512MB). CLIProxyAPI may struggle."
        log_warn "Consider increasing swap or using a larger instance."
    fi

    # Check port availability
    if ss -tlnp | grep -q ":${PORT}"; then
        log_error "Port ${PORT} is already in use!"
        log_error "Set CLIPROXYAPI_PORT environment variable to use a different port."
        exit 1
    fi

    log_info "Port ${PORT} is available"
}

create_user() {
    log_info "Creating service user..."

    if ! id -u ${SERVICE_USER} >/dev/null 2>&1; then
        useradd -r -s /bin/false -d ${INSTALL_DIR} ${SERVICE_USER}
        log_info "User ${SERVICE_USER} created"
    else
        log_info "User ${SERVICE_USER} already exists"
    fi
}

create_directories() {
    log_info "Creating directories..."

    mkdir -p ${INSTALL_DIR}
    mkdir -p ${CONFIG_DIR}
    mkdir -p ${AUTH_DIR}
    mkdir -p ${LOG_DIR}

    # Set permissions
    chmod 755 ${INSTALL_DIR}
    chmod 755 ${CONFIG_DIR}
    chmod 700 ${AUTH_DIR}  # Auth dir should be restrictive
    chmod 755 ${LOG_DIR}

    chown -R ${SERVICE_USER}:${SERVICE_GROUP} ${INSTALL_DIR}
    chown -R ${SERVICE_USER}:${SERVICE_GROUP} ${LOG_DIR}

    log_info "Directories created"
}

download_binary() {
    log_info "Downloading CLIProxyAPI ${CLIPROXYAPI_VERSION}..."

    DOWNLOAD_URL="https://github.com/router-for-me/CLIProxyAPI/releases/download/${CLIPROXYAPI_VERSION}/${BINARY_NAME}"
    BINARY_PATH="${INSTALL_DIR}/cliproxyapi"

    wget -q -O ${BINARY_PATH} ${DOWNLOAD_URL}
    chmod +x ${BINARY_PATH}

    log_info "Binary downloaded to ${BINARY_PATH}"
}

create_config() {
    log_info "Creating configuration file..."

    cat > ${CONFIG_DIR}/config.yaml << 'EOF'
# CLIProxyAPI Configuration
# Auto-generated by install script

server:
  host: "127.0.0.1"
  port: PORT_PLACEHOLDER

auth-dir: "AUTH_DIR_PLACEHOLDER"

log-level: "info"

# Providers are configured via CLI authentication:
#   ./cliproxyapi -gemini-login
#   ./cliproxyapi -iflow-cookie    # IMPORTANT: use cookie, not OAuth!
#   ./cliproxyapi -antigravity-login
#   ./cliproxyapi -qwen-login

routing:
  strategy: round-robin
  fallback-enabled: true
  retry-attempts: 3
  timeout-seconds: 120

health:
  enabled: true
  interval-seconds: 30
EOF

    # Replace placeholders
    sed -i "s|PORT_PLACEHOLDER|${PORT}|g" ${CONFIG_DIR}/config.yaml
    sed -i "s|AUTH_DIR_PLACEHOLDER|${AUTH_DIR}|g" ${CONFIG_DIR}/config.yaml

    log_info "Configuration created at ${CONFIG_DIR}/config.yaml"
}

create_systemd_service() {
    log_info "Creating systemd service..."

    cat > /etc/systemd/system/cliproxyapi.service << EOF
[Unit]
Description=CLIProxyAPI - OAuth Router for LLM Providers
Documentation=https://help.router-for.me/
After=network.target network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${SERVICE_USER}
Group=${SERVICE_GROUP}
WorkingDirectory=${INSTALL_DIR}
ExecStart=${INSTALL_DIR}/cliproxyapi --config ${CONFIG_DIR}/config.yaml
ExecReload=/bin/kill -HUP \$MAINPID

# Resource limits (critical for 1GB VPS)
MemoryMax=100M
CPUQuota=50%

# Restart policy
Restart=on-failure
RestartSec=10

# Security hardening
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=${AUTH_DIR} ${LOG_DIR}

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=cliproxyapi

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    log_info "Systemd service created"
}

enable_service() {
    log_info "Enabling service..."

    systemctl enable cliproxyapi
    log_info "Service enabled to start on boot"
}

print_post_install() {
    echo ""
    echo "=========================================="
    echo " CLIProxyAPI Installation Complete!"
    echo "=========================================="
    echo ""
    echo "Binary:     ${INSTALL_DIR}/cliproxyapi"
    echo "Config:     ${CONFIG_DIR}/config.yaml"
    echo "Auth:       ${AUTH_DIR}/"
    echo "Logs:       journalctl -u cliproxyapi"
    echo ""
    echo "NEXT STEPS:"
    echo ""
    echo "1. Set up providers (run as root or use sudo):"
    echo ""
    echo "   ${INSTALL_DIR}/cliproxyapi -gemini-login"
    echo "   ${INSTALL_DIR}/cliproxyapi -iflow-cookie     # USE COOKIE, NOT OAUTH!"
    echo "   ${INSTALL_DIR}/cliproxyapi -antigravity-login"
    echo "   ${INSTALL_DIR}/cliproxyapi -qwen-login"
    echo ""
    echo "   IMPORTANT: For iFlow, use -iflow-cookie (NOT -iflow-login)!"
    echo "   OAuth tokens expire every 7 days. Cookie auth auto-refreshes."
    echo ""
    echo "2. Start the service:"
    echo ""
    echo "   sudo systemctl start cliproxyapi"
    echo ""
    echo "3. Check status:"
    echo ""
    echo "   sudo systemctl status cliproxyapi"
    echo "   curl http://127.0.0.1:${PORT}/health"
    echo ""
    echo "4. Test a request:"
    echo ""
    echo "   curl http://127.0.0.1:${PORT}/v1/models"
    echo ""
    echo "5. Configure your gateway to use CLIProxyAPI:"
    echo ""
    echo "   CLIPROXYAPI_ENABLED=true"
    echo "   CLIPROXYAPI_BASE_URL=http://127.0.0.1:${PORT}"
    echo ""
}

# Main execution
main() {
    log_info "Starting CLIProxyAPI installation..."
    echo ""

    check_requirements
    create_user
    create_directories
    download_binary
    create_config
    create_systemd_service
    enable_service

    print_post_install

    log_info "Installation completed successfully!"
}

main "$@"
